apiVersion: v1
kind: ConfigMap
metadata:
  name: listings-api-config
  labels: {{- include "keh.labels" (dict "ctx" . "name" "listings-api") | nindent 4 }}
data:
  {{- range $k, $v := .Values.listingsApi.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  ENVIRONMENT: {{ .Values.environment | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migrations
  labels: {{- include "keh.labels" (dict "ctx" . "name" "db-migrate") | nindent 4 }}
data:
{{ (.Files.Glob "files/db/*").AsConfig | indent 2 }}
