{{- include "keh.validate" . -}}
{{- if .Values.namespaceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kubeestatehub-quota
  labels: {{- include "keh.labels" (dict "ctx" . "name" "kubeestatehub") | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.namespaceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.namespaceQuota.requestsMemory }}
    limits.cpu: {{ .Values.namespaceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.namespaceQuota.limitsMemory }}
    persistentvolumeclaims: "10"
    requests.storage: 500Gi
    pods: "60"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kubeestatehub-defaults
  labels: {{- include "keh.labels" (dict "ctx" . "name" "kubeestatehub") | nindent 4 }}
spec:
  limits:
    - type: Container
      min: {cpu: 10m, memory: 16Mi}
      defaultRequest: {cpu: 50m, memory: 64Mi}
      default: {cpu: "1", memory: 256Mi}
      max: {cpu: "4", memory: 4Gi}
{{- end }}
