# Location: `/helm-charts/kubeestatehub/templates/secrets.yaml`

{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-db-secret
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  username: {{ .Values.global.postgresql.auth.username | b64enc }}
  password: {{ .Values.global.postgresql.auth.password | b64enc }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.global.postgresql.auth.username .Values.global.postgresql.auth.password (include "kubeestatehub.fullname" .) .Values.global.postgresql.auth.database | b64enc }}
---
{{- end }}

{{- if .Values.imageStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-minio-secret
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  root-user: {{ .Values.imageStore.auth.rootUser | b64enc }}
  root-password: {{ .Values.imageStore.auth.rootPassword | b64enc }}
---
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-global-secret
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
data:
  JWT_SECRET_KEY: {{ randAlphaNum 32 | b64enc }}
  JWT_ALGORITHM: {{ "HS256" | b64enc }}
  JWT_EXPIRATION_HOURS: {{ "24" | b64enc }}
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc }}
  SIGNING_KEY: {{ randAlphaNum 32 | b64enc }}