# Location: `/helm-charts/kubeestatehub/templates/serviceaccounts.yaml`

{{- if .Values.serviceAccounts.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeestatehub.serviceAccountName" . }}
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.automountServiceAccountToken | default true }}
---
{{- end }}

{{- if .Values.serviceAccounts.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-listings-api
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: listings-api
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
{{- end }}

{{- if .Values.serviceAccounts.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-analytics-worker
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics-worker
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
{{- end }}

{{- if .Values.serviceAccounts.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-frontend-dashboard
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-dashboard
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
{{- end }}

{{- if and .Values.serviceAccounts.create .Values.imageStore.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-image-store
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-store
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
{{- end }}

{{- if and .Values.serviceAccounts.create .Values.monitoring.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeestatehub.fullname" . }}-monitoring
  labels:
    {{- include "kubeestatehub.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
{{- end }}