{{- range $name := list "listings-api" "frontend" "metrics-service" "analytics" "postgres" "redis" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels: {{- include "keh.labels" (dict "ctx" $ "name" $name) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
