#!/usr/bin/env python3
"""Regenerate derived manifests from their single sources of truth.

  db/migrate.sh + db/migrations/*.sql   -> manifests/base/db-migrations-configmap.yaml
                                           helm-charts/kubeestatehub/files/db/
  observability/prometheus/rules.yaml   -> manifests/components/monitoring/prometheusrule.yaml
                                           helm-charts/kubeestatehub/files/rules.yaml
  manifests/components/operator/crd.yaml -> helm-charts/kubeestatehub/crds/realestatesyncs.yaml
  manifests/components/{admission-policy,backup} -> helm-charts/kubeestatehub/templates/
  hack/dashboards.py                    -> observability/grafana/*.json
                                           manifests/components/monitoring/grafana-dashboards.yaml
                                           helm-charts/kubeestatehub/files/dashboards/

CI runs `make verify-generated`, which fails if any output differs from what is committed.
Standard library only.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "hack"))
import dashboards  # noqa: E402

HEADER = "# GENERATED by hack/generate.py - do not edit by hand.\n"
CHART_FILES = ROOT / "helm-charts" / "kubeestatehub" / "files"


def block(text: str, indent: int) -> str:
    pad = " " * indent
    return "\n".join(pad + line if line else "" for line in text.rstrip("\n").split("\n")) + "\n"


def configmap(name: str, files: dict[str, str], labels: dict[str, str] | None = None) -> str:
    out = [HEADER, "apiVersion: v1\n", "kind: ConfigMap\n", "metadata:\n", f"  name: {name}\n"]
    if labels:
        out.append("  labels:\n")
        out += [f'    {k}: "{v}"\n' for k, v in labels.items()]
    out.append("data:\n")
    for key in sorted(files):
        out.append(f"  {key}: |\n")
        out.append(block(files[key], 4))
    return "".join(out)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text() != content:
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


def sync_dir(src_files: dict[str, str], dest: Path) -> None:
    if dest.exists():
        for stale in dest.iterdir():
            if stale.name not in src_files:
                stale.unlink()
                print(f"removed {stale.relative_to(ROOT)}")
    for name, content in src_files.items():
        write(dest / name, content)


def main() -> None:
    db = {p.name: p.read_text() for p in sorted((ROOT / "db" / "migrations").glob("*.sql"))}
    db["migrate.sh"] = (ROOT / "db" / "migrate.sh").read_text()
    write(ROOT / "manifests/base/db-migrations-configmap.yaml", configmap("db-migrations", db))
    sync_dir(db, CHART_FILES / "db")

    rules = (ROOT / "observability/prometheus/rules.yaml").read_text()
    rule_body = rules[rules.index("groups:"):]
    write(
        ROOT / "manifests/components/monitoring/prometheusrule.yaml",
        HEADER + "apiVersion: monitoring.coreos.com/v1\nkind: PrometheusRule\nmetadata:\n  name: kubeestatehub\n"
        "  labels:\n    app.kubernetes.io/part-of: kubeestatehub\nspec:\n" + block(rule_body, 2),
    )
    write(CHART_FILES / "rules.yaml", rule_body)

    rendered = {name: json.dumps(fn(), indent=2) + "\n" for name, fn in dashboards.DASHBOARDS.items()}
    for name, content in rendered.items():
        write(ROOT / "observability/grafana" / name, content)
    write(
        ROOT / "manifests/components/monitoring/grafana-dashboards.yaml",
        configmap("kubeestatehub-dashboards", rendered, labels={"grafana_dashboard": "1"}),
    )
    sync_dir(rendered, CHART_FILES / "dashboards")
    chart = ROOT / "helm-charts" / "kubeestatehub"
    components = ROOT / "manifests" / "components"
    write(chart / "crds" / "realestatesyncs.yaml", HEADER + (components / "operator" / "crd.yaml").read_text())
    policy = (components / "admission-policy" / "policy.yaml").read_text()
    policy = policy.replace("validationActions: [Deny]",
                            "validationActions: {{ toJson .Values.admissionPolicy.validationActions }}")
    policy = policy.replace("matchLabels: {kubernetes.io/metadata.name: kubeestatehub}",
                            "matchLabels: {kubernetes.io/metadata.name: {{ .Release.Namespace }}}")
    write(chart / "templates" / "admission-policy.yaml",
          HEADER + "{{- if .Values.admissionPolicy.enabled }}\n" + policy.rstrip() + "\n{{- end }}\n")
    backup = (components / "backup" / "backup.yaml").read_text()
    for old, new in (
        ("storage: 20Gi}}", "storage: {{ .Values.backup.storage }}}}"),
        ('schedule: "0 1 * * *"', "schedule: {{ .Values.backup.schedule | quote }}"),
        ('{name: BACKUP_RETENTION_DAYS, value: "14"}',
         "{name: BACKUP_RETENTION_DAYS, value: {{ .Values.backup.retentionDays | quote }}}"),
    ):
        if old not in backup:
            raise SystemExit(f"backup component changed; update hack/generate.py ({old!r})")
        backup = backup.replace(old, new)
    write(chart / "templates" / "backup.yaml",
          HEADER + "{{- if .Values.backup.enabled }}\n" + backup.rstrip() + "\n{{- end }}\n")
    shutil.rmtree(ROOT / "hack" / "__pycache__", ignore_errors=True)


if __name__ == "__main__":
    main()
